site_name: Sommelier DB & Drive Docs
site_url: https://sommelier-db.github.io/Sommelier-docs/
repo_url: https://github.com/Sommelier-db/Sommelier-docs/
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/figs/logo.png
  logo: assets/figs/logo.png
  language: en
  features:
    - navigation.tracking
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: "index.md"
  - Sommelier DB:
    - Introduction: "db/intro.md"
    - Get Started: "db/get_started.md"
    - How it works: "db/how_it_works.md"
    - APIs: "db/apis.md"
  - Sommelier Drive:
    - Introduction: "drive/intro.md"
    - Get Started: "drive/get_started.md"
    - How it works:
      - Overview: "drive/how_it_works/overview.md"
      - Server Specification: "drive/how_it_works/server_spec.md"
      - Client Specification: "drive/how_it_works/client_spec.md"
    - APIs:
      - Server REST APIs: "drive/apis/server_apis.md"
      - Client APIs: "drive/apis/client_apis.md"
  - Developer's Blog:
    - Public key searchable encryption: "blog/pkse.md"
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed
  - attr_list
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  # Latex
  - pymdownx.arithmatex:
      generic: true
extra:
  search:
    language: "en"
  analytics:
    provider: google
    property: G-XCVVGGTC1G
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - include-markdown
  - search:
      lang: en