site_name: Sommelier DB & Drive Docs
repo_url: https://github.com/Sommelier-db/Sommelier-docs/
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/figs/favicon.png
  logo: assets/figs/favicon.png
  language: en
  features:
    - navigation.tracking
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: "index.md"
  - Sommelier DB:
    - Introduction: "db/intro.md"
  - Sommelier Drive:
    - Introduction: "drive/intro.md"
  - Developer's Blog:
    - Public key searchable encryption: "blog/pkse.md"
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed
  - attr_list
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  # Latex
  - pymdownx.arithmatex:
      generic: true
extra:
  search:
    language: "en"
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - include-markdown
  - search:
      lang: en